apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
    containers:
      - name: jenkins
        image: auroobaparker/jenkins-application:latest  # Specify the image you want to deploy
        ports:
        - containerPort: 8080
